      double precision amp,amp2,ap,ap2,aml,aml2,al2,amc2,amh,
     .amt,tara,tarz,fermom,amm,amn,chbar,barn
      integer isf20
      common/cmp/amp,amp2,ap,ap2,aml,aml2,al2,amc2,amh,
     .amt,tara,tarz,fermom,amm,amn,chbar,barn,isf20
      data
     .amm/2.7928456d0/,amn/-1.913148d0/,chbar/.197328d0/,barn/.389379d6/
     .aml/.511000d-3/,aml2/.261112d-6/,al2/.522240d-6/,amc2/1.151857d0/,
     .amp/.938272d0/,amh/.938272d0/,
     .isf20/4/
